# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfazVentas.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from BaseDatos import BaseDatos
from Cliente import Cliente
import sqlite3
class Ui_ventasObject(object):
    def vincularCliente(self):
        existeCliente=self.clienteActual.buscarClienteDoc(self.lineEdit_clienteActivo.text())
        if existeCliente:
            palette = QtGui.QPalette()
            brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
            self.label_errorClienteActivo.setPalette(palette)
            self.label_errorClienteActivo.setText("VINCULACIÓN EXITOSA!")
            self.habilitarBotonesPrincipales()
            self.lineEdit_clienteActivo.setEnabled(False)
            self.pushButton_vincularCliente.setEnabled(False)
            self.label_nombre_clienteActivo.setText(self.clienteActual.nombreUsuario)
        else:
            palette = QtGui.QPalette()
            brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
            brush.setStyle(QtCore.Qt.SolidPattern)
            palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
            self.label_errorClienteActivo.setPalette(palette)
            self.label_errorClienteActivo.setText("DOC NO ENCONTRADO")

    def deshabilitarBotonesPrincipales(self):
        self.pushButton_agregarItemVenta.setEnabled(False)
        self.pushButton_confirmarVenta.setEnabled(False)
        self.lineEdit_clienteActivo.setEnabled(True)
        self.pushButton_vincularCliente.setEnabled(True)
    def habilitarBotonesPrincipales(self):
        self.pushButton_agregarItemVenta.setEnabled(True)
        self.pushButton_confirmarVenta.setEnabled(True)

    def setupUi(self, ventasObject):
        self.clienteActual=Cliente()
        ventasObject.setObjectName("ventasObject")
        ventasObject.resize(800, 600)
        ventasObject.setMinimumSize(QtCore.QSize(800, 600))
        ventasObject.setMaximumSize(QtCore.QSize(800, 600))
        ventasObject.setAcceptDrops(True)
        self.pushButton_vincularCliente = QtWidgets.QPushButton(ventasObject)
        self.pushButton_vincularCliente.setGeometry(QtCore.QRect(650, 90, 121, 31))
        self.pushButton_vincularCliente.setObjectName("pushButton_vincularCliente")
        self.label_ClienteActivo = QtWidgets.QLabel(ventasObject)
        self.label_ClienteActivo.setGeometry(QtCore.QRect(660, 0, 91, 31))
        self.label_ClienteActivo.setObjectName("label_ClienteActivo")
        self.label_id_clienteActivo = QtWidgets.QLabel(ventasObject)
        self.label_id_clienteActivo.setGeometry(QtCore.QRect(610, 30, 21, 21))
        self.label_id_clienteActivo.setObjectName("label_id_clienteActivo")
        self.label_nombre_clienteActivo = QtWidgets.QLabel(ventasObject)
        self.label_nombre_clienteActivo.setGeometry(QtCore.QRect(580, 70, 57, 14))
        self.label_nombre_clienteActivo.setObjectName("label_nombre_clienteActivo")
        self.lineEdit_clienteActivo = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_clienteActivo.setGeometry(QtCore.QRect(640, 30, 151, 26))
        self.lineEdit_clienteActivo.setObjectName("lineEdit_clienteActivo")
        self.label_errorClienteActivo = QtWidgets.QLabel(ventasObject)
        self.label_errorClienteActivo.setGeometry(QtCore.QRect(580, 130, 201, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 112, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_errorClienteActivo.setPalette(palette)
        self.label_errorClienteActivo.setObjectName("label_errorClienteActivo")
        self.label_mostrar_nombreClienteActivo = QtWidgets.QLabel(ventasObject)
        self.label_mostrar_nombreClienteActivo.setGeometry(QtCore.QRect(640, 70, 151, 16))
        self.label_mostrar_nombreClienteActivo.setText("")
        self.label_mostrar_nombreClienteActivo.setObjectName("label_mostrar_nombreClienteActivo")
        self.label_buscadorItems = QtWidgets.QLabel(ventasObject)
        self.label_buscadorItems.setGeometry(QtCore.QRect(220, 10, 131, 16))
        self.label_buscadorItems.setObjectName("label_buscadorItems")
        self.listWidget_buscarItems = QtWidgets.QListWidget(ventasObject)
        self.listWidget_buscarItems.setGeometry(QtCore.QRect(70, 90, 451, 91))
        self.listWidget_buscarItems.setObjectName("listWidget_buscarItems")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_buscarItems.addItem(item)
        self.tableWidget_itemVentas = QtWidgets.QTableWidget(ventasObject)
        self.tableWidget_itemVentas.setGeometry(QtCore.QRect(50, 350, 711, 171))
        self.tableWidget_itemVentas.setObjectName("tableWidget_itemVentas")
        self.tableWidget_itemVentas.setColumnCount(8)
        self.tableWidget_itemVentas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemVentas.setHorizontalHeaderItem(7, item)
        self.pushButton_confirmarVenta = QtWidgets.QPushButton(ventasObject)
        self.pushButton_confirmarVenta.setGeometry(QtCore.QRect(650, 550, 121, 31))
        self.pushButton_confirmarVenta.setObjectName("pushButton_confirmarVenta")
        self.pushButton_cancelarVenta = QtWidgets.QPushButton(ventasObject)
        self.pushButton_cancelarVenta.setGeometry(QtCore.QRect(510, 550, 121, 31))
        self.pushButton_cancelarVenta.setObjectName("pushButton_cancelarVenta")


        self.label_infoProducto = QtWidgets.QLabel(ventasObject)
        self.label_infoProducto.setGeometry(QtCore.QRect(50, 190, 211, 16))
        self.label_infoProducto.setObjectName("label_infoProducto")
        self.pushButton_agregarItemVenta = QtWidgets.QPushButton(ventasObject)
        self.pushButton_agregarItemVenta.setGeometry(QtCore.QRect(580, 280, 191, 51))
        self.pushButton_agregarItemVenta.setObjectName("pushButton_agregarItemVenta")
        self.label_codigo_item = QtWidgets.QLabel(ventasObject)
        self.label_codigo_item.setGeometry(QtCore.QRect(50, 220, 51, 21))
        self.label_codigo_item.setObjectName("label_codigo_item")
        self.lineEdit_codigo_Item = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_codigo_Item.setGeometry(QtCore.QRect(40, 240, 81, 26))
        self.lineEdit_codigo_Item.setObjectName("lineEdit_codigo_Item")
        self.label_descripcion = QtWidgets.QLabel(ventasObject)
        self.label_descripcion.setGeometry(QtCore.QRect(60, 280, 91, 16))
        self.label_descripcion.setObjectName("label_descripcion")
        self.label_descripcion_buscar = QtWidgets.QLabel(ventasObject)
        self.label_descripcion_buscar.setGeometry(QtCore.QRect(80, 40, 81, 16))
        self.label_descripcion_buscar.setObjectName("label_descripcion_buscar")
        self.label_codigo_buscar = QtWidgets.QLabel(ventasObject)
        self.label_codigo_buscar.setGeometry(QtCore.QRect(210, 40, 57, 14))
        self.label_codigo_buscar.setObjectName("label_codigo_buscar")
        self.spinBox_cantidadItem = QtWidgets.QSpinBox(ventasObject)
        self.spinBox_cantidadItem.setGeometry(QtCore.QRect(490, 300, 41, 24))
        self.spinBox_cantidadItem.setProperty("value", 1)
        self.spinBox_cantidadItem.setObjectName("spinBox_cantidadItem")
        self.comboBox_categoria_buscar = QtWidgets.QComboBox(ventasObject)
        self.comboBox_categoria_buscar.setGeometry(QtCore.QRect(300, 60, 141, 22))
        self.comboBox_categoria_buscar.setObjectName("comboBox_categoria_buscar")
        self.comboBox_categoria_buscar.addItem("")
        self.comboBox_categoria_buscar.addItem("")
        self.label_categoria_buscar = QtWidgets.QLabel(ventasObject)
        self.label_categoria_buscar.setGeometry(QtCore.QRect(320, 40, 57, 14))
        self.label_categoria_buscar.setObjectName("label_categoria_buscar")
        self.label_inventarioDisp = QtWidgets.QLabel(ventasObject)
        self.label_inventarioDisp.setGeometry(QtCore.QRect(160, 280, 91, 16))
        self.label_inventarioDisp.setObjectName("label_inventarioDisp")
        self.label_categoria_item = QtWidgets.QLabel(ventasObject)
        self.label_categoria_item.setGeometry(QtCore.QRect(260, 280, 91, 16))
        self.label_categoria_item.setObjectName("label_categoria_item")
        self.comboBox_itemDescuento = QtWidgets.QComboBox(ventasObject)
        self.comboBox_itemDescuento.setGeometry(QtCore.QRect(570, 240, 141, 22))
        self.comboBox_itemDescuento.setObjectName("comboBox_itemDescuento")
        self.comboBox_itemDescuento.addItem("")
        self.comboBox_itemDescuento.addItem("")
        self.label_cantidadItem = QtWidgets.QLabel(ventasObject)
        self.label_cantidadItem.setGeometry(QtCore.QRect(480, 280, 91, 16))
        self.label_cantidadItem.setObjectName("label_cantidadItem")
        self.label_descuento = QtWidgets.QLabel(ventasObject)
        self.label_descuento.setGeometry(QtCore.QRect(600, 220, 91, 16))
        self.label_descuento.setObjectName("label_descuento")
        self.lineEdit_mostrarDescripcionItem = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_mostrarDescripcionItem.setGeometry(QtCore.QRect(40, 300, 113, 26))
        self.lineEdit_mostrarDescripcionItem.setText("")
        self.lineEdit_mostrarDescripcionItem.setReadOnly(True)
        self.lineEdit_mostrarDescripcionItem.setClearButtonEnabled(False)
        self.lineEdit_mostrarDescripcionItem.setObjectName("lineEdit_mostrarDescripcionItem")
        self.lineEdit_mostrarInventarioDisp = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_mostrarInventarioDisp.setGeometry(QtCore.QRect(180, 300, 31, 26))
        self.lineEdit_mostrarInventarioDisp.setText("")
        self.lineEdit_mostrarInventarioDisp.setReadOnly(True)
        self.lineEdit_mostrarInventarioDisp.setClearButtonEnabled(False)
        self.lineEdit_mostrarInventarioDisp.setObjectName("lineEdit_mostrarInventarioDisp")
        self.lineEdit_mostrarCategoria = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_mostrarCategoria.setGeometry(QtCore.QRect(240, 300, 113, 26))
        self.lineEdit_mostrarCategoria.setText("")
        self.lineEdit_mostrarCategoria.setReadOnly(True)
        self.lineEdit_mostrarCategoria.setClearButtonEnabled(False)
        self.lineEdit_mostrarCategoria.setObjectName("lineEdit_mostrarCategoria")
        self.label_precio = QtWidgets.QLabel(ventasObject)
        self.label_precio.setGeometry(QtCore.QRect(170, 220, 91, 16))
        self.label_precio.setObjectName("label_precio")
        self.lineEdit_mostrarPrecioUnitario = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_mostrarPrecioUnitario.setGeometry(QtCore.QRect(160, 240, 113, 26))
        self.lineEdit_mostrarPrecioUnitario.setText("")
        self.lineEdit_mostrarPrecioUnitario.setReadOnly(True)
        self.lineEdit_mostrarPrecioUnitario.setClearButtonEnabled(False)
        self.lineEdit_mostrarPrecioUnitario.setObjectName("lineEdit_mostrarPrecioUnitario")
        self.label_infoProducto_2 = QtWidgets.QLabel(ventasObject)
        self.label_infoProducto_2.setGeometry(QtCore.QRect(360, 190, 341, 21))
        self.label_infoProducto_2.setObjectName("label_infoProducto_2")
        self.label_medioPago = QtWidgets.QLabel(ventasObject)
        self.label_medioPago.setGeometry(QtCore.QRect(400, 220, 91, 16))
        self.label_medioPago.setObjectName("label_medioPago")
        self.comboBox_item_medioPago = QtWidgets.QComboBox(ventasObject)
        self.comboBox_item_medioPago.setGeometry(QtCore.QRect(380, 240, 141, 22))
        self.comboBox_item_medioPago.setObjectName("comboBox_item_medioPago")
        self.comboBox_item_medioPago.addItem("")
        self.comboBox_item_medioPago.addItem("")
        self.lineEdit_descripcion_buscar = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_descripcion_buscar.setGeometry(QtCore.QRect(60, 60, 113, 26))
        self.lineEdit_descripcion_buscar.setObjectName("lineEdit_descripcion_buscar")
        self.lineEdit_codigo_buscar = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_codigo_buscar.setGeometry(QtCore.QRect(180, 60, 113, 26))
        self.lineEdit_codigo_buscar.setObjectName("lineEdit_codigo_buscar")
        self.label_errorCodigo = QtWidgets.QLabel(ventasObject)
        self.label_errorCodigo.setGeometry(QtCore.QRect(30, 560, 201, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 112, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_errorCodigo.setPalette(palette)
        self.label_errorCodigo.setText("")
        self.label_errorCodigo.setObjectName("label_errorCodigo")
        self.label_total_desc = QtWidgets.QLabel(ventasObject)
        self.label_total_desc.setGeometry(QtCore.QRect(250, 550, 91, 20))
        self.label_total_desc.setObjectName("label_total_desc")
        self.lineEdit_mostrarTotalConDesc = QtWidgets.QLineEdit(ventasObject)
        self.lineEdit_mostrarTotalConDesc.setGeometry(QtCore.QRect(340, 540, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_mostrarTotalConDesc.setFont(font)
        self.lineEdit_mostrarTotalConDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mostrarTotalConDesc.setReadOnly(True)
        self.lineEdit_mostrarTotalConDesc.setClearButtonEnabled(False)
        self.lineEdit_mostrarTotalConDesc.setObjectName("lineEdit_mostrarTotalConDesc")
        self.label_IVA = QtWidgets.QLabel(ventasObject)
        self.label_IVA.setGeometry(QtCore.QRect(400, 280, 41, 16))
        self.label_IVA.setObjectName("label_IVA")
        self.spinBox_IVA = QtWidgets.QSpinBox(ventasObject)
        self.spinBox_IVA.setGeometry(QtCore.QRect(400, 300, 41, 24))
        self.spinBox_IVA.setProperty("value", 19)
        self.spinBox_IVA.setObjectName("spinBox_IVA")
        self.pushButton_buscar = QtWidgets.QPushButton(ventasObject)
        self.pushButton_buscar.setGeometry(QtCore.QRect(460, 30, 71, 51))
        self.pushButton_buscar.setObjectName("pushButton_buscar")

        self.deshabilitarBotonesPrincipales()
        self.pushButton_cancelarVenta.clicked.connect(self.deshabilitarBotonesPrincipales)
        self.pushButton_vincularCliente.clicked.connect(self.vincularCliente)
        self.retranslateUi(ventasObject)
        QtCore.QMetaObject.connectSlotsByName(ventasObject)

    def retranslateUi(self, ventasObject):
        _translate = QtCore.QCoreApplication.translate
        ventasObject.setWindowTitle(_translate("ventasObject", "Ventas"))
        self.pushButton_vincularCliente.setText(_translate("ventasObject", "Vincular Cliente"))
        self.label_ClienteActivo.setText(_translate("ventasObject", "Cliente Activo:"))
        self.label_id_clienteActivo.setText(_translate("ventasObject", "Id: "))
        self.label_nombre_clienteActivo.setText(_translate("ventasObject", "Nombre: "))
        self.label_errorClienteActivo.setText(_translate("ventasObject", "VINCULE CLIENTE EXISTENTE"))
        self.label_buscadorItems.setText(_translate("ventasObject", "Buscador de items:"))
        __sortingEnabled = self.listWidget_buscarItems.isSortingEnabled()
        self.listWidget_buscarItems.setSortingEnabled(False)
        self.listWidget_buscarItems.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_itemVentas.horizontalHeaderItem(0)
        item.setText(_translate("ventasObject", "Codigo"))
        item = self.tableWidget_itemVentas.horizontalHeaderItem(1)
        item.setText(_translate("ventasObject", "Categoria"))
        item = self.tableWidget_itemVentas.horizontalHeaderItem(2)
        item.setText(_translate("ventasObject", "Precio"))
        item = self.tableWidget_itemVentas.horizontalHeaderItem(3)
        item.setText(_translate("ventasObject", "Cantidad"))
        item = self.tableWidget_itemVentas.horizontalHeaderItem(4)
        item.setText(_translate("ventasObject", "IVA"))
        item = self.tableWidget_itemVentas.horizontalHeaderItem(5)
        item.setText(_translate("ventasObject", "Total sin IVA"))
        item = self.tableWidget_itemVentas.horizontalHeaderItem(6)
        item.setText(_translate("ventasObject", "Total + IVA"))
        item = self.tableWidget_itemVentas.horizontalHeaderItem(7)
        item.setText(_translate("ventasObject", "Borrar"))
        self.pushButton_confirmarVenta.setText(_translate("ventasObject", "Confirmar Venta"))
        self.pushButton_cancelarVenta.setText(_translate("ventasObject", "Cancelar Venta"))
        self.label_infoProducto.setText(_translate("ventasObject", "Registro e Informacion de Producto:"))
        self.pushButton_agregarItemVenta.setText(_translate("ventasObject", "Agregar Item"))
        self.label_codigo_item.setText(_translate("ventasObject", "Codigo* "))
        self.label_descripcion.setText(_translate("ventasObject", "Descripcion"))
        self.label_descripcion_buscar.setText(_translate("ventasObject", "Descripcion"))
        self.label_codigo_buscar.setText(_translate("ventasObject", "Codigo"))
        self.comboBox_categoria_buscar.setItemText(0, _translate("ventasObject", "Frutas"))
        self.comboBox_categoria_buscar.setItemText(1, _translate("ventasObject", "Carnes"))
        self.label_categoria_buscar.setText(_translate("ventasObject", "Categorias"))
        self.label_inventarioDisp.setText(_translate("ventasObject", "Inv Disponible"))
        self.label_categoria_item.setText(_translate("ventasObject", "Categoria"))
        self.comboBox_itemDescuento.setItemText(0, _translate("ventasObject", "Sin Descuento"))
        self.comboBox_itemDescuento.setItemText(1, _translate("ventasObject", "Descuento 10%"))
        self.label_cantidadItem.setText(_translate("ventasObject", "Cantidad*"))
        self.label_descuento.setText(_translate("ventasObject", "Descuento"))
        self.label_precio.setText(_translate("ventasObject", "Precio Unitario"))
        self.label_infoProducto_2.setText(_translate("ventasObject", "Seleccione Descuento y Medio de Pago para toda la venta :"))
        self.label_medioPago.setText(_translate("ventasObject", "Medio de Pago"))
        self.comboBox_item_medioPago.setItemText(0, _translate("ventasObject", "Sin Descuento"))
        self.comboBox_item_medioPago.setItemText(1, _translate("ventasObject", "Descuento 10%"))
        self.label_total_desc.setText(_translate("ventasObject", "TOTAL - DESC:"))
        self.lineEdit_mostrarTotalConDesc.setText(_translate("ventasObject", "0"))
        self.label_IVA.setText(_translate("ventasObject", "IVA %"))
        self.pushButton_buscar.setText(_translate("ventasObject", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventasObject = QtWidgets.QWidget()
    ui = Ui_ventasObject()
    ui.setupUi(ventasObject)
    ventasObject.show()
    sys.exit(app.exec_())
