# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'productos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_productosForm(object):
    def setupUi(self, productosForm,usuarioActual):
        productosForm.setObjectName("productosForm")
        productosForm.resize(600, 498)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(productosForm.sizePolicy().hasHeightForWidth())
        productosForm.setSizePolicy(sizePolicy)
        productosForm.setMinimumSize(QtCore.QSize(600, 0))
        productosForm.setMaximumSize(QtCore.QSize(600, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(productosForm)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_Codigo = QtWidgets.QLineEdit(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Codigo.sizePolicy().hasHeightForWidth())
        self.lineEdit_Codigo.setSizePolicy(sizePolicy)
        self.lineEdit_Codigo.setObjectName("lineEdit_Codigo")
        self.verticalLayout_2.addWidget(self.lineEdit_Codigo)
        self.label_3 = QtWidgets.QLabel(productosForm)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_Precio = QtWidgets.QLineEdit(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Precio.sizePolicy().hasHeightForWidth())
        self.lineEdit_Precio.setSizePolicy(sizePolicy)
        self.lineEdit_Precio.setObjectName("lineEdit_Precio")
        self.verticalLayout_2.addWidget(self.lineEdit_Precio)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_Nombre = QtWidgets.QLineEdit(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Nombre.sizePolicy().hasHeightForWidth())
        self.lineEdit_Nombre.setSizePolicy(sizePolicy)
        self.lineEdit_Nombre.setObjectName("lineEdit_Nombre")
        self.verticalLayout_3.addWidget(self.lineEdit_Nombre)
        self.label_4 = QtWidgets.QLabel(productosForm)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lineEdit_proximo = QtWidgets.QLineEdit(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_proximo.sizePolicy().hasHeightForWidth())
        self.lineEdit_proximo.setSizePolicy(sizePolicy)
        self.lineEdit_proximo.setObjectName("lineEdit_proximo")
        self.verticalLayout_3.addWidget(self.lineEdit_proximo)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAdd = QtWidgets.QPushButton(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(productosForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)

        self.retranslateUi(productosForm)
        QtCore.QMetaObject.connectSlotsByName(productosForm)

    def retranslateUi(self, productosForm):
        _translate = QtCore.QCoreApplication.translate
        productosForm.setWindowTitle(_translate("productosForm", "Productos"))
        self.label.setText(_translate("productosForm", "Código"))
        self.label_3.setText(_translate("productosForm", "Precio"))
        self.label_2.setText(_translate("productosForm", "Nombre"))
        self.label_4.setText(_translate("productosForm", "Próximo atributo"))
        self.btnAdd.setText(_translate("productosForm", "Añadir"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("productosForm", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("productosForm", "Código"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("productosForm", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("productosForm", "Precio"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("productosForm", "Opciones"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    productosForm = QtWidgets.QWidget()
    ui = Ui_productosForm()
    ui.setupUi(productosForm)
    productosForm.show()
    sys.exit(app.exec_())
